/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        sidebar: '#0B101D',
        surface: '#0D1422',
        'surface-dim': '#0f131d',
        'surface-bright': '#353944',
        'surface-elevated': '#111C2D',
        'surface-container-lowest': '#0a0e17',
        'surface-container-low': '#171c25',
        'surface-container': '#1b2029',
        'surface-container-high': '#262a34',
        'surface-container-highest': '#31353f',
        'surface-variant': '#31353f',
        'surface-tint': '#4cd7f6',
        'border-subtle': '#1E293B',
        outline: '#869397',
        'outline-variant': '#3d494c',
        'text-primary': '#F8FAFC',
        'text-secondary': '#94A3B8',
        'text-disabled': '#64748B',
        'on-surface': '#dfe2f0',
        'on-surface-variant': '#bcc9cd',
        'inverse-surface': '#dfe2f0',
        'inverse-on-surface': '#2c303b',
        primary: '#4cd7f6',
        'primary-hover': '#0891B2',
        'primary-container': '#06b6d4',
        'on-primary': '#003640',
        'on-primary-container': '#00424f',
        secondary: '#c0c1ff',
        'secondary-container': '#3131c0',
        'on-secondary': '#1000a9',
        'on-secondary-container': '#b0b2ff',
        tertiary: '#ffb873',
        'tertiary-container': '#e89337',
        'on-tertiary': '#4b2800',
        'on-tertiary-container': '#5b3200',
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#F43F5E',
        error: '#ffb4ab',
        'error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
    },
  },
  plugins: [],
};
