/**
 * Seed Script - VIBE OS
 * Populates database with the 10 qualified leads from Manaus
 */

export const INITIAL_LEADS_MANAUS = [
  {
    nomeEmpresa: "Clínica Dra. Juliana Estética",
    nicho: "ESTETICA",
    localizacao: "Vieiralves, Manaus",
    linkBio: "https://linktr.ee/drajulianaestetica",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Sem site indexado. 100% dependente do Linktree e Instagram Direct.",
    nomeDecisor: "Dra. Juliana Vieira",
    cargoDecisor: "Proprietária / Biomédica Esteta",
    emailDecisor: "juliana@drajulianaestetica.com.br",
    phoneWhatsapp: "(92) 99123-4567",
    instagramUrl: "https://instagram.com/drajulianaestetica"
  },
  {
    nomeEmpresa: "Studio FitManaus Personal",
    nicho: "PERSONAL_TRAINER",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://docs.google.com/forms/fitmanaus",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Link da bio direciona para formulário genérico do Google Docs.",
    nomeDecisor: "Victor Belém",
    cargoDecisor: "Head Trainer / Sócio",
    emailDecisor: "victor@fitmanaus.com.br",
    phoneWhatsapp: "(92) 99234-5678",
    instagramUrl: "https://instagram.com/fitmanauspersonal"
  },
  {
    nomeEmpresa: "OdontoArt Manaus",
    nicho: "ODONTOLOGIA",
    localizacao: "Ponta Negra, Manaus",
    linkBio: "https://odontoartmanaus.com.br",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "ALTA",
    authorityScore: 8,
    trafegoOrganico: 45,
    palavrasChave: 12,
    percentSocial: 82.0,
    diagnosticoSeo: "Site em WordPress 2018 desatualizado, sem responsividade móvel.",
    nomeDecisor: "Dr. Fernando Alencar",
    cargoDecisor: "Cirurgião-Dentista / Sócio",
    emailDecisor: "fernando@odontoartmanaus.com.br",
    phoneWhatsapp: "(92) 99345-6789",
    instagramUrl: "https://instagram.com/odontoartmanaus"
  },
  {
    nomeEmpresa: "Harmonia & Face Estética",
    nicho: "ESTETICA",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://wa.me/5592994567890",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Link direto para o WhatsApp sem página de autoridade ou prova social.",
    nomeDecisor: "Dra. Camila Ramos",
    cargoDecisor: "Fundadora / Harmonizadora Facial",
    emailDecisor: "camila@harmoniaeface.com.br",
    phoneWhatsapp: "(92) 99456-7890",
    instagramUrl: "https://instagram.com/harmoniaeface"
  },
  {
    nomeEmpresa: "Ponto Um Performance",
    nicho: "PERSONAL_TRAINER",
    localizacao: "Vila da Prata, Manaus",
    linkBio: "https://instagram.com/pontoumperformance",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Zero presença de busca orgânica no Google Manaus.",
    nomeDecisor: "Lucas Santana",
    cargoDecisor: "Personal Trainer / Founder",
    emailDecisor: "lucas@pontoumperformance.com",
    phoneWhatsapp: "(92) 99567-8901",
    instagramUrl: "https://instagram.com/pontoumperformance"
  },
  {
    nomeEmpresa: "OdontoClin Adrianópolis",
    nicho: "ODONTOLOGIA",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://odontoclinadrianopolis.com.br",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "ALTA",
    authorityScore: 12,
    trafegoOrganico: 120,
    palavrasChave: 28,
    percentSocial: 74.0,
    diagnosticoSeo: "Taxa de rejeição de 74%, falta sistema automático de agendamento.",
    nomeDecisor: "Dra. Renata Castro",
    cargoDecisor: "Diretora Clínica",
    emailDecisor: "renata@odontoclinadrianopolis.com.br",
    phoneWhatsapp: "(92) 99678-9012",
    instagramUrl: "https://instagram.com/odontoclinadrianopolis"
  },
  {
    nomeEmpresa: "BellePeel Estética Integrativa",
    nicho: "ESTETICA",
    localizacao: "Centro, Manaus",
    linkBio: "https://bellepeel.wixsite.com/manaus",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 2,
    trafegoOrganico: 5,
    palavrasChave: 1,
    percentSocial: 95.0,
    diagnosticoSeo: "Subdomínio gratuito Wix sem SSL configurado e UX quebrada no celular.",
    nomeDecisor: "Mariana Duarte",
    cargoDecisor: "Sócia Proprietária",
    emailDecisor: "mariana@bellepeel.com.br",
    phoneWhatsapp: "(92) 99789-0123",
    instagramUrl: "https://instagram.com/bellepeelestetica"
  },
  {
    nomeEmpresa: "Coach Gabriel Fitness",
    nicho: "PERSONAL_TRAINER",
    localizacao: "Ponta Negra, Manaus",
    linkBio: "https://drive.google.com/file/d/pdf-consultoria",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Usa cartão PDF estático no Google Drive para apresentar planos.",
    nomeDecisor: "Gabriel Nogueira",
    cargoDecisor: "Personal Trainer / Consultor",
    emailDecisor: "gabriel@gabrielfitness.com.br",
    phoneWhatsapp: "(92) 99890-1234",
    instagramUrl: "https://instagram.com/coachgabrielfitness"
  },
  {
    nomeEmpresa: "Sorriso Prime Odontologia",
    nicho: "ODONTOLOGIA",
    localizacao: "Vieiralves, Manaus",
    linkBio: "https://sorrisoprime.com.br",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "ALTA",
    authorityScore: 15,
    trafegoOrganico: 80,
    palavrasChave: 35,
    percentSocial: 68.0,
    diagnosticoSeo: "Queda de 60% no tráfego orgânico no último semestre por falta de atualização.",
    nomeDecisor: "Dr. Marcelo Fonseca",
    cargoDecisor: "Proprietário / Implantodonte",
    emailDecisor: "marcelo@sorrisoprime.com.br",
    phoneWhatsapp: "(92) 99901-2345",
    instagramUrl: "https://instagram.com/sorrisoprimeodonto"
  },
  {
    nomeEmpresa: "Instituto Renovah Estética",
    nicho: "ESTETICA",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://instagram.com/institutorenovah",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Instagram forte (25k), porém sem landing page para conversão direta.",
    nomeDecisor: "Dra. Patricia Siqueira",
    cargoDecisor: "Médica Dermatologista / CEO",
    emailDecisor: "patricia@institutorenovah.com.br",
    phoneWhatsapp: "(92) 99012-3456",
    instagramUrl: "https://instagram.com/institutorenovah"
  }
];
