import { Lead, Projeto } from '../types/crm';

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-1",
    nomeEmpresa: "Clínica Dra. Juliana Estética",
    nicho: "ESTETICA",
    localizacao: "Vieiralves, Manaus",
    linkBio: "https://linktr.ee/drajulianaestetica",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Sem site indexado. 100% dependente do Linktree e Instagram Direct.",
    nomeDecisor: "Dra. Juliana Vieira",
    cargoDecisor: "Proprietária / Biomédica Esteta",
    emailDecisor: "juliana@drajulianaestetica.com.br",
    phoneWhatsapp: "(92) 99123-4567",
    instagramUrl: "https://instagram.com/drajulianaestetica",
    valorEstimado: 2400,
    interacoes: [
      {
        id: "int-1",
        leadId: "lead-1",
        tipo: "NOTA",
        conteudo: "Diagnóstico gerado via DataForSEO. Perfil altamente qualificado para Site de Agendamento.",
        autor: "Growth Engine AIsa",
        createdAt: "2026-10-01T14:30:00Z"
      }
    ],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-01T14:30:00Z"
  },
  {
    id: "lead-2",
    nomeEmpresa: "Studio FitManaus Personal",
    nicho: "PERSONAL_TRAINER",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://docs.google.com/forms/fitmanaus",
    status: "ABORDADO_WHATSAPP",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Link da bio direciona para formulário genérico do Google Docs.",
    nomeDecisor: "Victor Belém",
    cargoDecisor: "Head Trainer / Sócio",
    emailDecisor: "victor@fitmanaus.com.br",
    phoneWhatsapp: "(92) 99234-5678",
    instagramUrl: "https://instagram.com/fitmanauspersonal",
    valorEstimado: 1800,
    interacoes: [
      {
        id: "int-2",
        leadId: "lead-2",
        tipo: "WHATSAPP",
        conteudo: "Enviada mensagem auditando o formulário do Google Docs e oferecendo protótipo de alta conversão.",
        autor: "SDR Outbound",
        createdAt: "2026-10-02T09:15:00Z"
      }
    ],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-02T09:15:00Z"
  },
  {
    id: "lead-3",
    nomeEmpresa: "OdontoArt Manaus",
    nicho: "ODONTOLOGIA",
    localizacao: "Ponta Negra, Manaus",
    linkBio: "https://odontoartmanaus.com.br",
    status: "REUNIAO_AGENDADA",
    urgencia: "ALTA",
    authorityScore: 8,
    trafegoOrganico: 45,
    palavrasChave: 12,
    percentSocial: 82.0,
    diagnosticoSeo: "Site em WordPress 2018 desatualizado, sem responsividade móvel.",
    nomeDecisor: "Dr. Fernando Alencar",
    cargoDecisor: "Cirurgião-Dentista / Sócio",
    emailDecisor: "fernando@odontoartmanaus.com.br",
    phoneWhatsapp: "(92) 99345-6789",
    instagramUrl: "https://instagram.com/odontoartmanaus",
    valorEstimado: 3500,
    interacoes: [
      {
        id: "int-3",
        leadId: "lead-3",
        tipo: "REUNIAO",
        conteudo: "Reunião de alinhamento agendada para Quinta-feira às 15:30 via Google Meet.",
        autor: "Victor (VIBE)",
        createdAt: "2026-10-02T10:00:00Z"
      }
    ],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z"
  },
  {
    id: "lead-4",
    nomeEmpresa: "Harmonia & Face Estética",
    nicho: "ESTETICA",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://wa.me/5592994567890",
    status: "PROPOSTA_ENVIADA",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Link direto para o WhatsApp sem página de autoridade ou prova social.",
    nomeDecisor: "Dra. Camila Ramos",
    cargoDecisor: "Fundadora / Harmonizadora Facial",
    emailDecisor: "camila@harmoniaeface.com.br",
    phoneWhatsapp: "(92) 99456-7890",
    instagramUrl: "https://instagram.com/harmoniaeface",
    valorEstimado: 2800,
    interacoes: [
      {
        id: "int-4",
        leadId: "lead-4",
        tipo: "PROPOSTA",
        conteudo: "Proposta de Landing Page Premium + Sistema de Agendamento enviada por e-mail e PDF no Whats.",
        autor: "Comercial VIBE",
        createdAt: "2026-10-02T11:00:00Z"
      }
    ],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-02T11:00:00Z"
  },
  {
    id: "lead-5",
    nomeEmpresa: "Ponto Um Performance",
    nicho: "PERSONAL_TRAINER",
    localizacao: "Vila da Prata, Manaus",
    linkBio: "https://instagram.com/pontoumperformance",
    status: "ABORDADO_EMAIL",
    urgencia: "CRITICA",
    authorityScore: 0,
    trafegoOrganico: 0,
    palavrasChave: 0,
    percentSocial: 100.0,
    diagnosticoSeo: "Zero presença de busca orgânica no Google Manaus.",
    nomeDecisor: "Lucas Santana",
    cargoDecisor: "Personal Trainer / Founder",
    emailDecisor: "lucas@pontoumperformance.com",
    phoneWhatsapp: "(92) 99567-8901",
    instagramUrl: "https://instagram.com/pontoumperformance",
    valorEstimado: 1500,
    interacoes: [],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-01T14:00:00Z"
  },
  {
    id: "lead-6",
    nomeEmpresa: "OdontoClin Adrianópolis",
    nicho: "ODONTOLOGIA",
    localizacao: "Adrianópolis, Manaus",
    linkBio: "https://odontoclinadrianopolis.com.br",
    status: "FECHADO",
    urgencia: "MEDIA",
    authorityScore: 14,
    trafegoOrganico: 120,
    palavrasChave: 35,
    percentSocial: 65.0,
    diagnosticoSeo: "Necessita de otimização de velocidade de carregamento (LCP 4.2s) e captura de leads.",
    nomeDecisor: "Dra. Renata Mello",
    cargoDecisor: "Diretora Clínica",
    emailDecisor: "renata@odontoclinadrianopolis.com.br",
    phoneWhatsapp: "(92) 99678-9012",
    instagramUrl: "https://instagram.com/odontoclinadrianopolis",
    valorEstimado: 3200,
    interacoes: [
      {
        id: "int-6",
        leadId: "lead-6",
        tipo: "PROPOSTA",
        conteudo: "Contrato assinado! Sinal de 50% pago. Iniciando onboarding de projeto.",
        autor: "Gestor de Contratacoes",
        createdAt: "2026-10-02T08:30:00Z"
      }
    ],
    createdAt: "2026-10-01T14:00:00Z",
    updatedAt: "2026-10-02T08:30:00Z"
  },
  {
    id: "lead-7",
    nomeEmpresa: "Dermato Care Manaus",
    nicho: "MEDICINA",
    localizacao: "Nossa Senhora das Graças, Manaus",
    linkBio: "https://dermatocare.com.br",
    status: "LEAD_NOVO",
    urgencia: "ALTA",
    authorityScore: 5,
    trafegoOrganico: 20,
    palavrasChave: 8,
    percentSocial: 90.0,
    diagnosticoSeo: "Página sem HTTPS ativo e sem botão para WhatsApp.",
    nomeDecisor: "Dr. André Martins",
    cargoDecisor: "Dermatologista Titular",
    emailDecisor: "andre@dermatocare.com.br",
    phoneWhatsapp: "(92) 99789-0123",
    instagramUrl: "https://instagram.com/dermatocaremanaus",
    valorEstimado: 2900,
    interacoes: [],
    createdAt: "2026-10-02T10:00:00Z",
    updatedAt: "2026-10-02T10:00:00Z"
  },
  {
    id: "lead-8",
    nomeEmpresa: "Advocacia Castro & Assis",
    nicho: "ADVOCACIA",
    localizacao: "Centro, Manaus",
    linkBio: "https://castroassis.adv.br",
    status: "DIAGNOSTICO_GERADO",
    urgencia: "MEDIA",
    authorityScore: 12,
    trafegoOrganico: 95,
    palavrasChave: 28,
    percentSocial: 50.0,
    diagnosticoSeo: "Site institucional antigo sem blog de artigos de SEO Jurídico (OAB compliant).",
    nomeDecisor: "Dr. Roberto Castro",
    cargoDecisor: "Sócio Administrador",
    emailDecisor: "roberto@castroassis.adv.br",
    phoneWhatsapp: "(92) 99890-1234",
    instagramUrl: "https://instagram.com/castroassisadv",
    valorEstimado: 4500,
    interacoes: [],
    createdAt: "2026-10-02T10:30:00Z",
    updatedAt: "2026-10-02T10:30:00Z"
  }
];

export const INITIAL_PROJECTS: Projeto[] = [
  {
    id: "proj-1",
    leadId: "lead-6",
    nomeEmpresa: "OdontoClin Adrianópolis",
    clientName: "Dra. Renata Mello",
    nicho: "ODONTOLOGIA",
    projectType: "Presença Própria",
    status: "EM_PRODUCAO",
    riskLevel: "NORMAL",
    valorTotal: 3200,
    valorSinal: 1600,
    prazoDias: 7,
    dataInicio: "2026-10-02T08:30:00Z",
    dataPrevisao: "2026-10-09T08:30:00Z",
    checklistNormas: true,
    progress: 35,
    ownerName: "Operações VIBE"
  }
];
